### ISSUE TITLE
Creating directed edges using Constructor

### ISSUE THREAD

**Issue by skepticfx** [tantalor/graphjs#1]
I feel, this should have the ability to create a graph with directed edges using the new operator. Bu default, new Graph() creates a non-directed graph.

Does this feature already exist?

**Comment by tantalor** [comment]
Good idea. Any suggestion for the syntax?

**Comment by skepticfx** [comment]
Well. Naturally, we can have one more object which can do this as the second parameter. So that, we can add new things in the future as well.

var g = new Graph({
  a: ['b'],
  b: ['c'],
}, {directed: true}); // Created a new graph with directed edges.

var g = new Graph({
  a: ['b'],
  b: ['c'],
}, {directed: false}); 
// Equivalent to currently implemented, new Graph({
  a: ['b'],
  b: ['c'],
});

What do you think?

**Comment by tantalor** [comment]
I worry that the new option sounds like it changes the behavior of the
object when it really only changes the meaning of the input parameter.

Let me think a little more.

**Comment by skepticfx** [comment]
Makes sense.
Or we can leave, new Graph() as it is and have another method to do the same.
Like,

```
var g = new Graph();
g.addDirectedGraph({
a: ['b'],
b: ['c'],
});
```

**Comment by tantalor** [comment]
How does this look?

```
new Graph({a: ['-b', '-c']}); # Directed edges to b and c.
```

See https://github.com/tantalor/graphjs/commit/b398b9a6830baf8a328393e93f79027dec4df2a8

I realize this requires you to specify each edge as directed, rather than the whole lot like you originally asked for. I just thought this syntax might be more useful and the least confusing I could think of.

**Comment by skepticfx** [comment]
Makes sense. Thanks for the changes :+1:

**Comment by tantalor** [comment]
You're welcome, I'm happy to help. That change is merged into master branch now.

**Comment by skepticfx** [comment]
Great ! NPM is updated as well?

**Comment by tantalor** [comment]
Version 0.2.0 published right now.

**Comment by skepticfx** [comment]
:+1:
